server {
    listen 80;
    server_name localhost;
    root /srv/sulu/public;

    # Glavna lokacija za Sulu
    location / {
        try_files $uri /index.php$is_args$args;
    }

    # Obdelava PHP datotek
    location ~ ^/index\.php(/|$) {
        # POPRAVLJENO: Kaže nazaj na "sulu-php" servis
        fastcgi_pass sulu-php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;

        # Ključni popravki za Docker Port Mapping (81 -> 80),
        # da Sulu pravilno prepozna URL-je in odpravi UrlMatchNotFoundException
        fastcgi_param HTTP_HOST $http_host;
        fastcgi_param SERVER_PORT 81;
        fastcgi_param HTTP_X_FORWARDED_PORT 81;
        fastcgi_param HTTP_X_FORWARDED_HOST $host;

        internal;
    }

    # Logi za lažje razhroščevanje
    error_log /var/log/nginx/project_error.log;
    access_log /var/log/nginx/project_access.log;
}
